services:
  postgres:
    image: postgres:latest
    container_name: postgresRest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: myDataBase
    volumes:
      - postgres:/var/lib/postgres/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadminRest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8000:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin

  app:
#    image: "sha256:64d32bda33f742a235a3ba1ab3b826116c8a43761efa9460727d1c3eb9c3001e"
    image: "sha256:035348bdb2b30b08973148e75ab3c2a9e24a3bf281d826c572e7583a187467f7"
    container_name: app
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_URL=jdbc:postgresql://postgres:5432/myDataBase
    depends_on:
      - pgadmin

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafkaRest
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://:9093,PLAINTEXT_EXTERNAL://:9092,CONTROLLER://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:9093,PLAINTEXT_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

#  kafka:
#    image: confluentinc/cp-kafka:latest
#    container_name: kafkaRest
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_NODE_ID: 1
#      KAFKA_PROCESS_ROLES: broker,controller
#      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
#      KAFKA_CONSUMER_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_REPLICATION_FACTOR: 1
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
#      KAFKA_NUM_PARTITIONS: 1
#      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

volumes:
  postgres:
  pgadmin: